# Numpy Fundamental

In [1]:
!pip install numpy

You should consider upgrading via the 'C:\Users\thapa\Desktop\AI ML Workshop\streamlit\env\Scripts\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])

In [4]:
print("1D Array",arr1)

1D Array [1 2 3 4 5]


In [6]:
arr2=np.array([[1,2],[3,4]])
print("2D Array:\n",arr2)

2D Array:
 [[1 2]
 [3 4]]


In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])

In [4]:
print("Array\n",arr)

Array
 [[1 2 3]
 [4 5 6]]


In [5]:
print("Shape:",arr.shape)

Shape: (2, 3)


In [8]:
print("Dimenaions:",arr.ndim)

Dimenaions: 2


In [7]:
print("DataType:",arr.dtype)

DataType: int64


# 3D Array

In [19]:
arr_3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [21]:
print("3 Dim Array\n",arr_3d)

3 Dim Array
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
print("Dimention:",arr_3d.ndim)

Dimention: 3


In [24]:
print("Shape:",arr_3d.shape)

Shape: (2, 2, 2)


# Array Creation Funtions

In [26]:
zeros=np.zeros((2,3))
print("Zeros\n",zeros)

Zeros
 [[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
ones=np.ones((3,3))
print("Ones\n",ones)

Ones
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Range of values

In [33]:
range_arr=np.arange(0,10,2) # 0-10 value and 2 is step
print("Range:", range_arr)

Range: [0 2 4 6 8]


# Array Operations

In [36]:
arr=np.array([1,2,3,4,5])
print("Original Array\n",arr)

Original Array
 [1 2 3 4 5]


In [37]:
print("Add 5\n",arr+5)

Add 5
 [ 6  7  8  9 10]


In [40]:
print("Multiply by 2\n",arr*2)

Multiply by 2
 [ 2  4  6  8 10]


In [41]:
print("Square\n",arr**2)

Square
 [ 1  4  9 16 25]


# Reshaping Array

In [43]:
import numpy as np

In [44]:
arr=np.array([1,2,3,4,5,6])
print("Reshaping Array\n", arr.reshape(2,3))

Reshaping Array
 [[1 2 3]
 [4 5 6]]
